name: Build and Package

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone the osquery-packaging repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: osquery-packaging

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install all dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install requests
        pip install pyqt5

    - name: Create python script into app
      working-directory: osquery-packaging
      run: |
        pyinstaller --onefile vistar.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: vistar exe
        path: osquery-packaging/dist/vistar.exe

    - name: set up CMake
      run: |
        echo "OSQUERY_VERSION=5.10.2" >> $GITHUB_ENV
        cmake -DCMAKE_BUILD_TYPE=Release ^
            -DCPACK_GENERATOR=WIX ^
            -DOSQUERY_PACKAGE_VERSION=${{ env.OSQUERY_VERSION }} ^
            -DOSQUERY_DATA_PATH=osquery-packaging/Windows ^
            -S osquery-packaging ^
            -B package_build
        cmake --build package_build ^
          --target package


    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Vistar 1
        path: package_build/*.msi
